[book]
title = "Pewpew Guide"
authors = []
multilingual = false
src = "src"
build-dir = "book"

[output.html]
no-section-label = true
preferred-dark-theme = "ayu"
additional-css = ["src/custom.css"]
additional-js = ["src/version-banner.js"]
site-url = "/pewpew/"
