on:
  pull_request:

name: Pull Request Javascript
jobs:
  test-release:
    name: Build project
    strategy:
      matrix:
        node-version: [24.x, 26.x]
        runner: [ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Add Node.js toolchain ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm ci
      - run: npm run linterror
      - run: npm run build:react
      - name: Run Tests
        run: NODE_ENV=test npm test
