on:
  pull_request:

name: Pull Request Javascript
jobs:
  test-release:
    name: Build project
    strategy:
      matrix:
        node-version: [20.x, 22.x]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Add Node.js toolchain ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm ci
      - run: npm run linterror
      - run: npm run build:react
      - name: Run Tests
        run: NODE_ENV=test npm test
