language: rust
cache: cargo
os:
  - linux
  - osx
  - windows
dist: focal

env:
  - NODE_VERSION="12"

rust:
  - stable
branches:
  only:
    - master
before_install:
  - cargo install rustfmt
  - cargo install clippy
  - cargo install --version 0.9.0 cargo-deny
  - cargo install --version 0.10.0 wasm-pack
  - nvm install $NODE_VERSION
  - node --version

script:
  - cargo build
  - cargo test --all
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cargo fmt --all -- --check
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cargo clippy --all -- -D warnings
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cargo deny check --hide-inclusion-graph license sources advisories
    fi
  # - Wasm build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd ./lib/config-wasm
      wasm-pack build --release -t nodejs --scope fs
      cd tests/
      npm ci
      npm test
      cd ../../..
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd ./lib/hdr-histogram-wasm
      wasm-pack build --release -t nodejs --scope fs
      cd tests/
      npm ci
      npm test
      cd ../../..
    fi

# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: npm run publish
#     on:
#       branch: master