language: rust
cache: cargo
os:
  - linux
  - osx
  - windows

rust:
  - stable
branches:
  only:
    - master
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/artifactory/api/npm/fs-npm-prod-virtual/" >> ~/.npmrc
  - cargo install rustfmt
  - cargo install clippy
  - cargo install --version 0.9.0 cargo-deny

script:
  - cargo build
  - cargo test --all
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D warnings
  - cargo deny check --hide-inclusion-graph license sources advisories
  # - Wasm build

# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: npm run publish
#     on:
#       branch: master