[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-ld"
rustflags = ["-Ctarget-feature=+lse", "-Ctarget-cpu=neoverse-n1"]

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
