[graph]
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-unknown-linux-musl" },
    { triple = "armv7-unknown-linux-musleabihf" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "wasm32-unknown-unknown" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
version = 2
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0421",
]

[licenses]
private = { ignore = true }
version = 2
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
