[package]
name = "pewpew-config-updater"
edition = "2021"
version.workspace = true
license.workspace = true
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
config = { workspace = true, features = ["convert"] }
env_logger = "0.10"
log.workspace = true
