on:
  pull_request:

name: Pull Request Javascript
jobs:
  test-release:
    name: Build project
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    runs-on: ubuntu-latest
    # env:
    #   USE_XVFB: true

    steps:
      - uses: actions/checkout@v4

      - name: Add Node.js toolchain ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm ci
      - name: Run Tests
        run: NODE_ENV=test npm test
