import type { Route } from "next";

export const PAGE_START_TEST: Route = "/test";
export const PAGE_START_TEST_FORMAT = (testId: string, edit?: boolean): Route => `${PAGE_START_TEST}?testId=${testId}${edit ? "&edit" : ""}` as Route;
export const PAGE_TEST_HISTORY: Route = "/";
export const PAGE_TEST_HISTORY_FORMAT = (testId: string): Route => `${PAGE_TEST_HISTORY}?testId=${testId}` as Route;
export const PAGE_TEST_UPDATE: Route = "/testupdate";
export const PAGE_TEST_UPDATE_FORMAT = (testId: string): Route => `${PAGE_TEST_UPDATE}?testId=${testId}` as Route;
export const PAGE_CALENDAR: Route = "/calendar";
export const PAGE_ADMIN: Route = "/admin";
export const PAGE_LOGIN: Route = "/login";

export const API_AUTH: Route = "/api/auth" as Route;
export const API_ERROR: Route = "/api/error" as Route;
export const API_ERROR_FORMAT = (s3Folder: string): Route => `${API_ERROR}/${s3Folder}` as Route;
export const API_HEALTHCHECK: Route = "/api/healthcheck" as Route;
export const API_HEALTHCHECK_HEARTBEAT: Route = API_HEALTHCHECK + "/heartbeat" as Route;
export const API_HEALTHCHECK_S3: Route = API_HEALTHCHECK + "/s3" as Route;
export const API_HEALTHCHECK_SQS: Route = API_HEALTHCHECK + "/sqs" as Route;
export const API_JSON: Route = "/api/json" as Route;
export const API_JSON_FORMAT = (s3Folder: string, filename: string): Route => `${API_JSON}/${s3Folder}/${filename}` as Route;
export const API_LOGIN: Route = "/api/login" as Route;
export const API_LOGOUT: Route = "/api/logout" as Route;
export const API_PEWPEW: Route = "/api/pewpew" as Route;
export const API_QUEUE_NAMES: Route = "/api/queuenames" as Route;
export const API_QUEUES: Route = "/api/queues" as Route;
export const API_SCHEDULE: Route = "/api/schedule" as Route;
export const API_SCHEDULE_FORMAT = (testId: string): Route => `${API_SCHEDULE}?testId=${testId}` as Route;
export const API_SEARCH: Route = "/api/search" as Route;
export const API_SEARCH_FORMAT = (searchString: string): Route => `${API_SEARCH}?s3Folder=${searchString}` as Route;
export const API_STOP: Route = "/api/stop" as Route;
export const API_STOP_FORMAT = (testId: string, killTest?: boolean): Route => `${API_STOP}?testId=${testId}${killTest ? "&kill=true" : ""}` as Route;
export const API_TEST: Route = "/api/test" as Route;
export const API_TEST_FORMAT = (testId: string): Route => `${API_TEST}?testId=${testId}` as Route;
export const API_TEST_STATUS: Route = "/api/teststatus" as Route;
export const API_TEST_STATUS_FORMAT = (testId: string): Route => `${API_TEST_STATUS}?testId=${testId}` as Route;
export const API_YAML: Route = "/api/yaml" as Route;
export const API_YAML_FORMAT = (s3Folder: string, filename: string): Route => `${API_YAML}/${s3Folder}/${filename}` as Route;
export const API_DOWNLOAD: Route = "/api/download" as Route;
export const API_DOWNLOAD_FORMAT = (testId: string, filename?: string): Route => `${API_DOWNLOAD}?testId=${testId}${filename ? `&file=${filename}` : ""}` as Route;
