export const PAGE_START_TEST: string = "/test";
export const PAGE_TEST_HISTORY: string = "/";
export const PAGE_TEST_UPDATE: string = "/testupdate";
export const PAGE_CALENDAR: string = "/calendar";
export const PAGE_YAML_WRITER: string = "/yamlwriter";
export const PAGE_ADMIN: string = "/admin";
export const PAGE_LOGIN: string = "/login";

export const API_AUTH: string = "/api/auth";
export const API_ERROR: string = "/api/error";
export const API_ERROR_FORMAT = (s3Folder: string) => `${API_ERROR}/${s3Folder}`;
export const API_HEALTHCHECK: string = "/api/healthcheck";
export const API_HEALTHCHECK_HEARTBEAT: string = API_HEALTHCHECK + "/heartbeat";
export const API_HEALTHCHECK_S3: string = API_HEALTHCHECK + "/s3";
export const API_HEALTHCHECK_SQS: string = API_HEALTHCHECK + "/sqs";
export const API_JSON: string = "/api/json";
export const API_JSON_FORMAT = (s3Folder: string, filename: string) => `${API_JSON}/${s3Folder}/${filename}`;
export const API_INSTANCE_METRICS: string = "/api/instancemetrics";
export const API_LOGIN: string = "/api/login";
export const API_LOGOUT: string = "/api/logout";
export const API_PEWPEW: string = "/api/pewpew";
export const API_QUEUE_NAMES: string = "/api/queuenames";
export const API_QUEUES: string = "/api/queues";
export const API_SCHEDULE: string = "/api/schedule";
export const API_SEARCH: string = "/api/search";
export const API_STOP: string = "/api/stop";
export const API_TEST: string = "/api/test";
export const API_TEST_STATUS: string = "/api/teststatus";
export const API_YAML: string = "/api/yaml";
export const API_YAML_FORMAT = (s3Folder: string, filename: string) => `${API_YAML}/${s3Folder}/${filename}`;
