#!/usr/bin/env bash
source /home/fs/.nvm/nvm.sh
nvm install v18
 
# Environment variables are not passed to our run-build hook/script. Hard code them in the script
export NODE_ENV=production
export LoggingLevel=info
export LoggingLevelConsole=warn

# Now run whatever node or npm commands you need to run
npm run build
