#!/usr/bin/env bash
source /home/fs/.nvm/nvm.sh
nvm install v24

# Environment variables are not passed to our run-build hook/script. Hard code them in the script
# And platform scripts are not available on the build server either.
# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/custom-platforms-scripts.html
# NODE_ENV=$( /opt/elasticbeanstalk/bin/get-config environment -k NODE_ENV )
export NODE_ENV=production
export BASE_PATH=/pewpew/load-test
export AUTH_MODE=okta
export LOGGING_LEVEL=info
export LOGGING_LEVEL_CONSOLE=fatal
echo "BASE_PATH: \"${BASE_PATH}\""

# Now run whatever node or npm commands you need to run
npm run build
