on:
  pull_request:
    paths:
      - '**.js*'
      - '**.ts*'
      - '**.html'
      - '**/package.json'
      - '**/package-lock.json'

name: Pull Request Javascript
jobs:
  create-release:
    name: Build guide
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - name: Add Node.js toolchain ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Results Viewer and Book ${{ matrix.node-version }}
        run: |
          set -x
          # install mdbook and wasm-pack
          mkdir ~/bin
          PATH=$PATH:~/bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.20/mdbook-v0.4.20-x86_64-unknown-linux-gnu.tar.gz \
            | tar -xz -C ~/bin
          curl -sSL https://github.com/rustwasm/wasm-pack/releases/download/v0.11.0/wasm-pack-v0.11.0-x86_64-unknown-linux-musl.tar.gz \
            | tar -xz --strip-components=1 -C ~/bin --no-anchored wasm-pack

          # setup some envs to various paths for convenience
          PROJECT_ROOT=$PWD
          GUIDE_DIR=$(realpath $PROJECT_ROOT/guide)
          RESULTS_VIEWER_REACT_DIR=$(realpath $GUIDE_DIR/results-viewer-react)
          WASM_LIB_DIR=$(realpath $PROJECT_ROOT/lib/hdr-histogram-wasm)
          WASM_OUTPUT_REACT_DIR=$RESULTS_VIEWER_REACT_DIR/lib/hdr-histogram-wasm

          # build the hdr-histogram-wasm for the results viewer
          cd $WASM_LIB_DIR
          wasm-pack build --release -t bundler -d $WASM_OUTPUT_REACT_DIR --scope fs

          cd $RESULTS_VIEWER_REACT_DIR
          npm ci
          npm run linterror
          npm run build

          # build the book
          cd $GUIDE_DIR
          mdbook build
