on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.html'
      - '**/package.json'
      - '**/package-lock.json'

name: Pull Request Javascript
jobs:
  create-release:
    name: Build guide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - name: Add Node.js toolchain
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build Results Viewer and Book
        run: |
          set -x
          # install mdbook and wasm-pack
          mkdir ~/bin
          PATH=$PATH:~/bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.12/mdbook-v0.4.12-x86_64-unknown-linux-gnu.tar.gz \
            | tar -xz -C ~/bin

          curl -sSL https://github.com/rustwasm/wasm-pack/releases/download/v0.10.0/wasm-pack-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
            | tar -xz --strip-components=1 -C ~/bin --no-anchored wasm-pack

          # setup some envs to various paths for convenience
          PROJECT_ROOT=$PWD
          GUIDE_DIR=$(realpath $PROJECT_ROOT/guide)
          RESULTS_VIEWER_DIR=$(realpath $GUIDE_DIR/results-viewer)
          WASM_LIB_DIR=$(realpath $PROJECT_ROOT/lib/hdr-histogram-wasm)
          WASM_OUTPUT_DIR=$RESULTS_VIEWER_DIR/lib/hdr-histogram-wasm

          # build the hdr-histogram-wasm for the results viewer
          cd $WASM_LIB_DIR
          wasm-pack build --release -t web -d $WASM_OUTPUT_DIR
          cd $WASM_OUTPUT_DIR
          sed -i 's/input = .*import\.meta\.url.*/import(".\/hdr_histogram_wasm_bg.wasm");\ninput = require.resolve(".\/hdr_histogram_wasm_bg.wasm")[0][0];/' hdr_histogram_wasm.js

          # build the results viewer (which includes putting the output into the book's src)
          cd $RESULTS_VIEWER_DIR
          npm ci
          npm run build

          # build the book
          cd $GUIDE_DIR
          mdbook build
